/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.utilidades;

/**
 *
 * @author mauriballes
 */
public class Ayuda {

    public static final String HELP_GLOBAL = "Bienvenido!!!\n\n"
            + "A continuacion se listaran los comandos disponibles para interactuar con el sistema\n"
            + "Para acceder a la documentacion de cada uno, enviar el nombre del comando seguido de la palabra HELP\n\n"
            + "INSERTARCLIENTE\nINSERTARCLIENTE[\"Nombre Completo\",\"Contraseña\",Celular,Genero,\"Direccion\",\"Pagina Web\"] Genero: 1=varon, 2=mujer\n"
            + "MODIFICARCLIENTE\nMODIFICARCLIENTE[\"Nombre Completo\",\"Contraseña\",Celular,Genero,\"Direccion\",\"Pagina Web\"] Genero: 1=varon, 2=mujer\n"
            + "ELIMINARCLIENTE\nELIMINARCLIENTE\n"
            
            + "INSERTARCOMENTARIO\nINSERTARCOMENTARIO[\"Comentario\",Codigo Persona,Codigo Multimedia]\n"
            + "MODIFICARCOMENTARIO\nMODIFICARCOMENTARIO[Codigo Comentario,\"Comentario\",tu codigo,Codigo Multimedia]\n"
            + "ELIMINARCOMENTARIO\nELIMINARCOMENTARIO[Codigo Comentario]\n"
            + "LISTARCOMENTARIO\nLISTARCOMENTARIO[Codigo Multimedia]\n"
            
            + "INSERTARCONTACTO\nINSERTARCONTACTO[\"Correo contacto\"]\n"
            + "ELIMINARCONTACTO\nELIMINARCONTACTO[idcontacto]\n"
            + "LISTARCONTACTO\nLISTARCONTACTO\n"
            
            + "INSERTARDATOSPRINCIPALES\nINSERTARDATOSPRINCIPALES[\"Titulo\",\"Descripcion\",Su Codigo]\n"
            + "MODIFICARDATOSPRINCIPALES\nMODIFICARDATOSPRINCIPALES[Codigo De Dato Principal,\"Titulo\",\"Descripcion\",Su Codigo]\n"
            + "ELIMINARDATOSPRINCIPALES\nELIMINARDATOSPRINCIPALES[codigo]\n"
            + "LISTARDATOSPRINCIPALES\nLISTARDATOSPRINCIPALES[cod_cliente]\n"
            
            + "INSERTARMULTIMEDIA\nINSERTARMULTIMEDIA[\"Titulo\",Su Codigo] Envie un archivo adjunto[jpg,png,mp4,mkv]\n"
            + "MODIFICARMULTIMEDIA\nMODIFICARMULTIMEDIA[Codigo Multimedia,\"Titulo\",Su Codigo]\n"
            + "ELIMINARMULTIMEDIA\nELIMINARMULTIMEDIA[Codigo Multimedia]\n"
            + "LISTARMULTIMEDIA\nLISTARMULTIMEDIA\n"
            + "VERMULTIMEDIA\nVERMULTIMEDIA[Cod Multimedia]\n"

            
            + "INSERTARSUGERENCIA\nINSERTARSUGERENCIA[\"Correo a Recomentdar\",\"Comentario\",Su Codigo]\n"
            
            + "INSERTARUSUARIO\nINSERTARUSUARIO[\"Nombre Completo\",\"Correo\",\"Contraseña\",Celular,Genero,\"Empresa\"]\n"
            + "MODIFICARUSUARIO\nMODIFICARUSUARIO[\"Nombre Completo\",\"Correo\",\"Contraseña\",Celular,Genero,\"Empresa\"]\n"
            + "ELIMINARUSUARIO\nELIMINARUSUARIO\n"
             + "MOSTRARESTADISTICA\nMOSTRARESTADISTICA[Su Codigo]\n";
    public static final String HELP_INSERTARCLIENTE = "INSERTARCLIENTE!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es registrar a un cliente en el sistema.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- direccion (String con Comillas Dobles)\n"
            + "- web (String con Comillas Dobles)\n"
            + "INSERTARCLIENTE[\"direccion\",...]";
    public static final String HELP_MODIFICARCLIENTE = "Modificar Cliente!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es modificar a un cliente en el sistema.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- direccion (String con Comillas Dobles)\n"
            + "- web (String con Comillas Dobles)\n"
            + "\n"
            + "OPCIONALES: (Usar guion bajo \"_\" para decir no cambiar)\n"
            + "\n"
            + "id, direccion, web";
    public static final String HELP_ELIMINARCLIENTE = "Eliminar Cliente!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es Eliminar a un cliente registrados en el sistema,\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- id (Entero)\n"
            + "Mensaje:\n "
            + "\n"
            + "Eliminacion exitosa.";
    public static final String HELP_LISTARCLIENTE = "Lista De Registros!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es listar los registros de la tabla en el sistema,\n"
            + "no es necesario enviar ningun parametro";
    
    
    public static final String HELP_INSERTARCOMENTARIO = "Insertar Comentario!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es insertar a un comentario en el sistema.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- descripcion (String con Comillas Dobles)\n"
            + "- idMultimedia (Entero)\n"
            + "- idPersona (Entero)\n";
    public static final String HELP_MODIFICARCOMENTARIO = "Modificar Comentario!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es modificar un comentario en el sistema.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- codigo (Entero codigo de comentario)\n"
            + "- descripcion (String con Comillas Dobles)\n"
            + "- Codigo Persona (Entero)\n"
            + "\n"
            + "OPCIONALES: (Usar guion bajo \"_\" para decir no cambiar)\n"
            + "\n"
            + "codigo, descripcion, CodigoPersona";
    public static final String HELP_ELIMINARCOMENTARIO = "Eliminar Comentario!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es eliminar un comentario registrado en el sistema,\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- id (Entero)\n"
            + "Mensaje:\n "
            + "\n"
            + "Eliminacion exitosa.";
    public static final String HELP_LISTARCOMENTARIO = "Lista De Comentarios De Una Publicacion Multimedia!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es listar los registros de la tabla en el sistema,\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- Codigo Multimedia (Entero)\n";
    
    
    public static final String HELP_INSERTARCONTACTO = "Insertar Contacto!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es insertar a un contacto en el sistema.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- idcliente (Entero)\n"
            + "- idusuario (Entero)\n";
    public static final String HELP_ELIMINARCONTACTO = "Elimina Contacto!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es Eliminar a un contacto registrados en el sistema,\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- CodigoTrabajador (Entero)\n"
            + "- CodigoEmpleador (Entero)\n"
            + "Mensaje:\n "
            + "\n"
            + "Eliminacion exitosa.";
    public static final String HELP_LISTARCONTACTO = "Lista De Registros!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es listar los registros de la tabla en el sistema,\n"
            + "no es necesario enviar ningun parametros";
    
    
    public static final String HELP_INSERTARDATOSPRINCIPALES = "Insertar Datos Principales!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es insertar a un dato principal del cliente en el sistema.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- titulo (String con Comillas Dobles)\n"
            + "- descripcion (String con Comillas Dobles)\n"
            + "- idcliente (Entero)\n";
    public static final String HELP_MODIFICARDATOSPRINCIPALES = "Modificar Datos Principal!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es modificar un dato principal del cliente en el sistema.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- Codigo (Entero)\n"
            + "- titulo (String con Comillas Dobles)\n"
            + "- descripcion (String con Comillas Dobles)\n"
            + "- CodigoCliente (Entero)\n"
            + "\n"
            + "OPCIONALES: (Usar guion bajo \"_\" para decir no cambiar)\n"
            + "\n"
            + "Codigo,titulo, descripcion, idcliente";
    public static final String HELP_ELIMINARDATOSPRINCIPALES = "Eliminar Datos Principal!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es Eliminar a un dato principal registrados en el sistema,\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- id (Entero)\n"
            + "Mensaje:\n "
            + "\n"
            + "Eliminacion exitosa.";
    public static final String HELP_LISTARDATOSPRINCIPALES = "Lista De Registros!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es listar los registros de la tabla en el sistema,\n"
            + "no es necesario enviar ningun parametros";
    
    
    public static final String HELP_INSERTARMULTIMEDIA = "Insertar Multimedia!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es insertar a un archivo multimedia del cliente en el sistema.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- titulo (String con Comillas Dobles)\n"
            + "- tipo (Entero 1 si es foto 2 si es video)\n"
            + "- idcliente (Entero)\n";
    public static final String HELP_MODIFICARMULTIMEDIA = "Modificar Multimedia!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es modificar una publicidad multimedia en el sistema.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- Codigo (Entero)\n"
            + "- titulo (String con Comillas Dobles)\n"
            + "- tipo (Entero 1 si es foto 2 si es video)\n"
            + "- CodigoCiente (Entero)\n"
            + "\n"
            + "OPCIONALES: (Usar guion bajo \"_\" para decir no cambiar)\n"
            + "\n"
            + "Codigo,titulo, descripcion, CodigoCliente";
    public static final String HELP_ELIMINARMULTIMEDIA = "Eliminar Multimedia!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es Eliminar a un multimedia registrados en el sistema,\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- id (Entero)\n"
            + "Mensaje:\n "
            + "\n"
            + "Eliminacion exitosa.";
    public static final String HELP_LISTARMULTIMEDIA = "Lista De Registros!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es listar los registros de la tabla en el sistema,\n"
            + "no es necesario enviar ningun parametros";
    

    public static final String HELP_INSERTARPERSONA = "Insertar Persona!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es insertar a un registro de los datos de la persona en el sistema.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- nombre completo (String con Comillas Dobles)\n"
            + "- email (String con Comillas Dobles)\n"
            + "- password (String con Comillas Dobles)\n"
            + "- avatar 'imagen de perfil' (String con Comillas Dobles)\n"
            + "- celular (Entero)\n"
            + "- tipo (Entero 1 Trabajador'Personas que publican sus habilidades' 2 Empleador'Personas que buscan a personal trabajador ')\n"
            + "- genero (Entero 1 Masculino 2 Femenino)\n";
    public static final String HELP_MODIFICARPERSONA = "Modificar Persona!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es modificar los dato de la persona en el sistema.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- nombre completo (String con Comillas Dobles)\n"
            + "- email (String con Comillas Dobles)\n"
            + "- password (String con Comillas Dobles)\n"
            + "- avatar 'imagen de perfil' (String con Comillas Dobles)\n"
            + "- celular (Entero)\n"
            + "- genero (Entero 1 Masculino 2 Femenino)\n";
    public static final String HELP_ELIMINARPERSONA = "Eliminar Persona!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es Eliminar a una persona registrado en el sistema,\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- id (Entero)\n"
            + "Mensaje:\n "
            + "\n"
            + "Eliminacion exitosa.";
    public static final String HELP_LISTARPERSONA = "Lista De Registros!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es listar los registros de la tabla en el sistema,\n"
            + "no es necesario enviar ningun parametros";
    
    
    public static final String HELP_INSERTARSUGERENCIA = "Insertar Sugerencia!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es registrar una sugerencia con respecto a una publicacion multimedia en el sistema.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- idsugeridor (Entero)\n"
            + "- idreceptor (Entero)\n"
            + "- descripcion (String con Comillas Dobles)\n"
            + "- idmultimedia (Entero)\n";
    public static final String HELP_MODIFICARSUGERENCIA = "Modificar Sugerencia!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es modificar una sugerencia en el sistema.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- idsugeridor (Entero)\n"
            + "- idreceptor (Entero)\n"
            + "- descripcion (String con Comillas Dobles)\n"
            + "- idmultimedia (Entero)\n";
    public static final String HELP_ELIMINARSUGERENCIA = "Eliminar Sugerencia!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es Eliminar a una sugerencia registrado en el sistema,\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- id (Entero)\n"
            + "Mensaje:\n "
            + "\n"
            + "Eliminacion exitosa.";
    public static final String HELP_LISTARSUGERENCIA = "Lista De Registros!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es listar los registros de la tabla en el sistema,\n"
            + "no es necesario enviar ningun parametros";
    
    
    public static final String HELP_INSERTARUSUARIO = "Insertar Usuario!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es registrar un usuario en el sistema.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- nombre completo (String con Comillas Dobles)\n"
            + "- email (String con Comillas Dobles)\n"
            + "- password (String con Comillas Dobles)\n"
            + "- celular (Entero)\n"
            + "- tipo (Entero 1 Trabajador'Personas que publican sus habilidades' 2 Empleador'Personas que buscan a personal trabajador ')\n"
            + "- genero (Entero 1 Masculino 2 Femenino)\n"
            + "- empresa (String con Comillas Dobles)\n";
    public static final String HELP_MODIFICARUSUARIO = "Modificar Usuario!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es modificar un usuario en el sistema.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- Codigo (Entero)\n"
            + "- nombre completo (String con Comillas Dobles)\n"
            + "- password (String con Comillas Dobles)\n"
            + "- celular (Entero)\n"
            + "- genero (Entero 1 Masculino 2 Femenino)\n"
            + "- empresa (String con Comillas Dobles)\n";
    public static final String HELP_ELIMINARUSUARIO = "Eliminar Usuario!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es Eliminar a un usuario registrados en el sistema,\n"
            + "\n"
            + "PARAMETROS:\n"
            + "Mensaje:\n "
            + "\n"
            + "Eliminacion exitosa.";
    public static final String HELP_LISTARUSUARIO = "Lista De Registros!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es listar los registros de la tabla en el sistema,\n"
            + "no es necesario enviar ningun parametros";
    public static final String HELP_VERMULTIMEDIA = "VERMULTIMEDIA!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es mostrar el contenido multimeda.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- id (Entero, identificador de multimedia)\n"
            + "INSERTARCLIENTE[\"direccion\",...]";
    public static final String HELP_MOSTRARESTADISTICA = "MOSTRARESTADISTICA!!!\n"
            + "\n"
            + "Lo que hace el siguiente comando es mostrar la estadistica de un cliente.\n"
            + "\n"
            + "PARAMETROS:\n"
            + "\n"
            + "- id (Entero identificador de un cliente)\n"
            + "INSERTARCLIENTE[\"direccion\",...]";
}
